services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_PRIVATE_API_URL=http://backend:5000   # Interner Backend-Zugang
      - NEXT_PUBLIC_URL=http://${FRONTEND_PUBLIC_ADDRESS}:${FRONTEND_PUBLIC_PORT}  
    networks:
      - community_network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEXT_PUBLIC_URL=http://${FRONTEND_PUBLIC_ADDRESS}:${FRONTEND_PUBLIC_PORT}
    networks:
      - community_network

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    networks:
      - community_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - community_network

networks:
  community_network:
    driver: bridge

volumes:
  mongo_data:
